import React from 'react'
import TitlePage from '../components/main/title'
import GetDataForConsultingForm from '../components/consultationForm/GetDataForConsultingForm'
import Image from 'next/image'
import Link from 'next/link'
import { GoogleAnalytics } from '@next/third-parties/google'

export const metadata = {
  title: "Contact Us - Aqary Store | التواصل - برو ديل",
  description: "احصل علي استشارات مجانية الآن، عقارك هتلاقيه في عقاري، برو ديل هو الموقع العقاري الرائد في تجارة العقارات و الاستشارات العقارية و الاستثمارية في سواحل مصر و المدن الحديثة، استثمارك الآمن مع فريق عقاري - Generated By Rockai Dev",
};

export default function page() {
  return (
    <>
      <TitlePage />

      <section className='py-10 px-2'>
        <div className="contact sm:w-2/4 w-full">
          <GetDataForConsultingForm />
        </div>
        <div className="contacts my-10">
          <div className="head flex flex-wrap items-center justify-center">
            <Link href={'https://wa.me/201005511089?text=%7E%20%D9%81%D8%B1%D9%8A%D9%82%20%D9%85%D8%AA%D8%AC%D8%B1%20%D8%B9%D9%82%D8%A7%D8%B1%D9%8A'} className="link flex items-center justify-start bg-white hover:shadow-xl px-4 py-2 border rounded-xl duration-700 m-5 min-w-60">
              <Image src={'/whatsapp.png'} width={50} height={50} alt='Whatsapp Aqary Store' />
              <div className="text mr-2">
                <h3 className='text-black font-bold text-lg'>واتساب</h3>
                <h4>0100-551-1089</h4>
              </div>
            </Link>
            <Link href={'tel:+201005511089'} className="link flex items-center justify-start bg-white hover:shadow-xl px-4 py-2 border rounded-xl duration-700 m-5 min-w-60">
              <Image src={'/call.png'} width={50} height={50} alt='Whatsapp Aqary Store' />
              <div className="text mr-2">
                <h3 className='text-black font-bold text-lg'>اتصل بنا</h3>
                <h4>0100-551-1089</h4>
              </div>
            </Link>
            <Link href={'/'} className="link flex items-center justify-start bg-white hover:shadow-xl px-4 py-2 border rounded-xl duration-700 m-5 min-w-60">
              <Image src={'/website.png'} width={50} height={50} alt='Whatsapp Aqary Store' />
              <div className="text mr-2">
                <h3 className='text-black font-bold text-lg'>تفقد المزيد</h3>
                <h4>www.prodealeg.com</h4>
              </div>
            </Link>
          </div>
        </div>
        <div className="svgs absolute top-10 right-5 -z-10">
          <Image src={'/sendLocation.svg'} width={150} height={150} alt='send Message aqary Store' />
        </div>
      </section>
      <GoogleAnalytics gaId="G-3EVKQWKC3S" />
    </>

  )
}
