import ListData from '@/app/components/filter/ListData'
import TitlePage from '@/app/components/main/title'
import React from 'react'
import { GoogleAnalytics } from '@next/third-parties/google'

export const metadata = {
  title: "Real Estate Projects in Egypt - Aqary Store | مشاريع عقارية في مصر - متجر عقاري",
  description: "عقارك هتلاقيه في عقاري، متجر عقاري هو الموقع العقاري الرائد في تجارة العقارات و الاستشارات العقارية و الاستثمارية في سواحل مصر و المدن الحديثة، استثمارك الآمن مع فريق عقاري - Generated By Rockai Dev",
};

export default function page({ params }) {
  const { zoneName } = params

  return (
    <>
      <TitlePage />
      <section>
        <div className="title my-8 flex items-center justify-center flex-col text-center">
          <h3 className='text-3xl lg:text-5xl items-center font-black'>مشاريع للاستثمار في {decodeURIComponent(zoneName)}</h3>
        </div>

        <ListData showProject={true} showFilter={true} />
      </section>
      <GoogleAnalytics gaId="G-3EVKQWKC3S" />
    </>
  )
}
