
import React from 'react'
import { GoogleAnalytics } from '@next/third-parties/google'
import TitlePage from '../../../components/main/title';
import ListData from '../../../components/filter/ListData';

export const metadata = {
  title: "Real Estate Units in Egypt - Pro Deal | وحدات عقارية في مصر - برو ديل",
  description: "استثمر في الاناقة و عٍش في الرفاهية، برو ديل هو الموقع العقاري الرائد في تجارة العقارات و الاستشارات العقارية و الاستثمارية في سواحل مصر و المدن الحديثة، استثمارك الآمن مع فريق برو ديل - Generated By Rockai Dev",
};

export default function page({ params }) {
  const { zoneName } = params

  return (
    <>
      <TitlePage />
      <section>
        <div className="title my-8 flex items-center justify-center flex-col text-center">
          <h3 className='text-3xl lg:text-5xl items-center font-black'>وحدات للتملك في {decodeURIComponent(zoneName)}</h3>
        </div>
        <ListData showProperty={true} showFilter={true} />
      </section>
      <GoogleAnalytics gaId="G-3EVKQWKC3S" />
    </>
  )
}
