import "./globals.css";
import Header from "./components/main/Header";
import { NextAuthProvider } from "./Providers";
import Footer from "./components/main/Footer";
import { GoogleAnalytics } from '@next/third-parties/google'
import DataProvider from "./components/context/DataContext";

export const metadata = {
  title: "Pro Deal | برو ديل",
  description: "استثمر في الاناقة و عيشها برفاهية، متجر عقاري هو الموقع العقاري الرائد في تجارة العقارات و الاستشارات العقارية و الاستثمارية في سواحل مصر و المدن الحديثة، استثمارك الآمن مع فريق برو ديل - Generated By Rockai Dev",
};


export default async function RootLayout({ children }) {



  return (
    <html lang="ar" dir="rtl">
      <head>
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body className="text-textColor bg-bgColor flex items-center justify-center flex-col relative font-medium font-mainFont min-h-screen" suppressHydrationWarning={true}>

        <NextAuthProvider>
          <DataProvider>
            <Header />
            {children}
            <Footer />
          </DataProvider>
        </NextAuthProvider>
        <GoogleAnalytics gaId="G-3EVKQWKC3S" />
      </body>
    </html >
  );
}
