import TitlePage from '@/app/components/main/title'
import React from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { GoogleAnalytics } from '@next/third-parties/google'

export const metadata = {
    title: "Thank You - Pro Deal | شكراً لك - برو ديل",
    description: "عقارك هتلاقيه في عقاري، برو ديل هو الموقع العقاري الرائد في تجارة العقارات و الاستشارات العقارية و الاستثمارية في سواحل مصر و المدن الحديثة، استثمارك الآمن مع فريق عقاري - Generated By Rockai Dev",
};

export default function page() {
    return (
        <>
            <TitlePage />
            <section className='text-center p-2'>
                <div className="title my-4 flex items-center justify-center flex-col">
                    <h1 className="text-3xl lg:text-5xl items-center font-black">عقارك هتلاقيه في <span className="text-mainColor">عقــاري</span></h1>
                    <h3 className='mt-3 font-bold text-lg'>شكرأ لأهتمامك بالتواصل مع فريق برو ديل</h3>
                </div>

                <div className="my-10 flex items-center justify-center flex-col">
                    <div className="thankyou flex flex-col items-center justify-center">
                        <Image src={'/thanks.svg'} width={300} height={300} alt='thanks from Pro Deal' />
                        <h5 className='text-6xl font-black text-mainColor'>Thank you</h5>
                    </div>
                    <div className="head flex flex-wrap items-center justify-center">
                        <Link href={'https://wa.me/201005511089?text=%7E%20%D9%81%D8%B1%D9%8A%D9%82%20%D9%85%D8%AA%D8%AC%D8%B1%20%D8%B9%D9%82%D8%A7%D8%B1%D9%8A'} className="link flex items-center justify-start bg-white hover:shadow-xl px-4 py-2 border rounded-xl duration-700 m-5 min-w-60">
                            <Image src={'/whatsapp.png'} width={50} height={50} alt='Whatsapp Pro Deal' />
                            <div className="text mr-2">
                                <h3 className='text-black font-bold text-lg'>واتساب</h3>
                                <h4>0100-551-1089</h4>
                            </div>
                        </Link>
                        <Link href={'tel:+201005511089'} className="link flex items-center justify-start bg-white hover:shadow-xl px-4 py-2 border rounded-xl duration-700 m-5 min-w-60">
                            <Image src={'/call.png'} width={50} height={50} alt='Whatsapp Pro Deal' />
                            <div className="text mr-2">
                                <h3 className='text-black font-bold text-lg'>اتصل بنا</h3>
                                <h4>0100-551-1089</h4>
                            </div>
                        </Link>
                        <Link href={'/'} className="link flex items-center justify-start bg-white hover:shadow-xl px-4 py-2 border rounded-xl duration-700 m-5 min-w-60">
                            <Image src={'/website.png'} width={50} height={50} alt='Whatsapp Pro Deal' />
                            <div className="text mr-2">
                                <h3 className='text-black font-bold text-lg'>تفقد المزيد</h3>
                                <h4>www.prodealeg.com</h4>
                            </div>
                        </Link>
                    </div>

                </div>
            </section>
            <GoogleAnalytics gaId="G-3EVKQWKC3S" />
        </>
    )
}
