import React from 'react'
import TitlePage from '../components/main/title'
import Link from 'next/link'
import Image from 'next/image'
import { GoogleAnalytics } from '@next/third-parties/google'

const getZones = async () => {
  const apiUrl = process.env.API_URL; // استخدم NEXT_PUBLIC ليكون متاحًا على المتصفح

  if (!apiUrl) {
    console.error("❌ API_URL is missing! Set API_URL in .env");
    return null;
  }

  try {
    const res = await fetch(`${apiUrl}/api/zones`);

    if (!res.ok) {
      throw new Error(`❌ Failed to fetch zones: ${res.status} ${res.statusText}`);
    }

    const data = await res.json();
    return data;

  } catch (error) {
    console.error("🚨 Error fetching zones:", error.message);
    return []; // لتجنب كسر التطبيق
  }
};

export const metadata = {
  title: "Zones - Pro Deal | المناطق - برو ديل",
  description: "عقارك هتلاقيه في عقاري، متجر عقاري هو الموقع العقاري الرائد في تجارة العقارات و الاستشارات العقارية و الاستثمارية في سواحل مصر و المدن الحديثة، استثمارك الآمن مع فريق عقاري - Generated By Rockai Dev",
};

export default async function page() {
  const { zones } = await getZones()
  return (
    <>
      <TitlePage />
      <section>
        <div className="title my-4 flex items-center justify-center flex-col">
          <h3 className='text-3xl lg:text-5xl items-center font-black'>مناطق استثمارك في مصر</h3>
        </div>

        <div className="Zones flex flex-wrap items-center justify-center w-full">
          {zones.map(zone => (
            <Link key={zone._id} className='flex flex-col items-center m-3' href={`/zones/${zone.name}`}>
              <Image className='rounded-xl h-20' src={zone.image ? zone.image : '/city.png'} width={120} height={120} alt='city Icon' />
              <h2 className='text-textColor text-xl my-2 font-mainFont font-bold'>{zone.name}</h2>
              <div className="flex flex-row items-center justify-center my-2 font-mainFont font-bold">
                <div className="flex flex-col items-center justify-center mx-4">
                  <h3 className='text-sm'>{zone.projects.length}</h3>
                  <h4 className='text-sm'>مشروع</h4>
                </div>
                <div className="flex flex-col items-center justify-center mx-4">
                  <h3 className='text-sm'>{zone.properties.length}</h3>
                  <h4 className='text-sm'>وحدة</h4>
                </div>
              </div>
            </Link>
          ))}
        </div>

      </section>
            <GoogleAnalytics gaId="G-3EVKQWKC3S" />
    </>
  )
}
