import Menu from "./components/main/Menu";
import "./globals.css";

export const metadata = {
    title: "Dashboard - Pro Deal | لوحة التحكم - برو ديل",
    description: "استثمر في الاناقة و عٍش في الرفاهية، برو ديل هو الموقع العقاري الرائد في تجارة العقارات و الاستشارات العقارية و الاستثمارية في سواحل مصر و المدن الحديثة، استثمارك الآمن مع فريق برو ديل - Generated By Rockai Dev",
};

export default function RootLayout({ children }) {
    
    return (
        <main className="dashboard">
            <Menu />
            {children}
        </main>
    );
}