import React from 'react'
import Link from 'next/link'
import Image from 'next/image'
import { GoogleAnalytics } from '@next/third-parties/google'
import TitlePage from '../components/main/title';

const getDevelopers = async () => {
  const apiUrl = process.env.API_URL; // استخدم NEXT_PUBLIC_ عند الحاجة في العميل

  if (!apiUrl) {
    console.error("❌ API_URL is missing! Set NEXT_PUBLIC_API_URL in .env");
    return null;
  }

  try {
    const res = await fetch(`${apiUrl}/api/developers`);

    if (!res.ok) {
      throw new Error(`❌ Failed to fetch developers: ${res.status} ${res.statusText}`);
    }

    return await res.json();

  } catch (error) {
    console.error(`🚨 Error fetching developers:`, error.message);
    return null;
  }
};


export const metadata = {
  title: "Developers - Aqary Store | المطوريين - متجر عقاري",
  description: "عقارك هتلاقيه في عقاري، متجر عقاري هو الموقع العقاري الرائد في تجارة العقارات و الاستشارات العقارية و الاستثمارية في سواحل مصر و المدن الحديثة، استثمارك الآمن مع فريق عقاري - Generated By Rockai Dev",
};

export default async function page() {
  const { developers } = await getDevelopers()
  return (
    <>
      <TitlePage />
      <section>
        <div className="title my-4 flex items-center justify-center flex-col">
          <h3 className='text-3xl lg:text-5xl items-center font-black'>المطورين الرائدين لاستثمارك في مصر</h3>
        </div>

        <div className="developers flex flex-wrap items-center justify-center w-full">
          {developers?.map(developer => (
            <Link key={developer._id} className='min-w-80 flex flex-col items-center justify-between m-3 p-2' href={`/developers/${developer.name}`}>
              <div className="image h-40 rounded-full overflow-hidden shadow-xl border-2">
                <Image src={developer.image} className='w-full h-full' width={100} height={100} alt='city Icon' />
              </div>
              <h2 className='text-textColor text-xl my-2 font-mainFont font-bold'>{developer.name}</h2>
              <div className="flex flex-row items-center justify-center my-2 font-mainFont font-bold">
                <div className="flex flex-col items-center justify-center mx-4">
                  <h3 className='text-sm'>{developer.projects.length}</h3>
                  <h4 className='text-sm'>مشروع</h4>
                </div>
                <div className="flex flex-col items-center justify-center mx-4">
                  <h3 className='text-sm'>{developer.properties.length}</h3>
                  <h4 className='text-sm'>وحدة</h4>
                </div>
              </div>
            </Link>
          ))}
        </div>

      </section>
      <GoogleAnalytics gaId="G-3EVKQWKC3S" />
    </>
  )
}
